#!/bin/sh
#
# Start mdev....
#referred from https://github.com/cu-ecen-aeld/buildroot-assignments-base/pull/14/commits/110402f9f3b0b5af76fc5f7b0f9771ed228afb10

case "$1" in
  start)
	echo "Starting mdev..."
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	/sbin/mdev -s
	# coldplug modules
	find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | \
	    xargs -0 modprobe -abq
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
